### ISSUE TITLE
CSS COnflict

### ISSUE THREAD

**Issue by EmmyGuy** [OSSAdmiral/Recruit#119]
### Laravel Version

v10

### PHP Version

PhP 8.1

### Problem description

Good day.

Nice work team!

There seems to be a CSS conflict on the application page:

@vite('resources/css/career.css')
@vite('resources/css/career-job-post.css') (both called in app.blade.php file)
The above CSS files cause the input text to be invisible.

PS: I tried fixing the above, but I am a kind of newbie on the tailwind n filament, etc.

### Expected behavior

like on the admin create candidate, input texts are supposed to be white on black background!

### Steps to reproduce

To reproduce, select a job opening 
Try filling out the form

**Comment by MarJose123** [comment]
Hi @EmmyGuy, can you share more information, I've tried it on my end and I can't reproduce the issue that you have encountered.
